// Monta supabase/migrations/20260911130000_mesclagem_com_identidade_divergente.sql a partir dos
// blocos que gen_mesclagem_declarada.js copiou mecanicamente das funcoes VIGENTES.
//
//   node scratchpad/gen_mesclagem_declarada.js && node scratchpad/gen_mesclagem_declarada_montar.js
const fs = require('fs')
const path = require('path')

const RAIZ = path.join(__dirname, '..')
const SAIDA = path.join(RAIZ, 'supabase/migrations/20260911130000_mesclagem_com_identidade_divergente.sql')
const EOL = '\r\n' // convencao do projeto; os blocos gerados ja vem assim (o gerador confere)

function abortar(msg) { console.error(`\n[ABORTADO] ${msg}`); process.exit(1) }

const imp = fs.readFileSync(path.join(__dirname, '_imp_gerada.sql'), 'utf8')
const mesc = fs.readFileSync(path.join(__dirname, '_mesc_gerada.sql'), 'utf8')
for (const [nome, b] of [['impedimentos', imp], ['mesclagem', mesc]]) {
  if (!b.includes('p_confirmar_identidade')) abortar(`bloco ${nome} sem a declaracao — rode o gerador antes`)
  if (!b.includes('\r\n')) abortar(`bloco ${nome} nao esta em CRLF`)
}

const L = (...linhas) => linhas.join(EOL)

const CABECALHO = L(
  '-- ============================================================================',
  '-- MESCLAGEM COM IDENTIDADE DIVERGENTE — quando o CPF errado E O DEFEITO',
  '-- ============================================================================',
  '-- 11/09/2026',
  '--',
  '-- O PROBLEMA. A mesclagem de cadastros duplicados sempre exigiu o MESMO CPF nos dois lados, e',
  '-- por um motivo que continua valendo: o CPF e o dado que diz que os dois cadastros descrevem a',
  '-- mesma pessoa, e mesclar pessoas diferentes e o pior erro que esta ferramenta comete — o ponto',
  '-- de uma vira ponto da outra, e nao ha desfazer.',
  '--',
  '-- So que existe o caso oposto, e ele apareceu em producao: o cadastro foi refeito com um CPF',
  '-- de OUTRA pessoa. Ai o CPF divergente nao e o sinal de que sao duas pessoas — e o proprio erro',
  '-- que se quer corrigir.',
  '--',
  '-- 🚨 E A SAIDA QUE A MENSAGEM MANDAVA SEGUIR ERA CIRCULAR. O texto do impedimento dizia',
  '-- "corrija o CPF errado na ficha antes de mesclar". Gravar na ficha o CPF que ja esta no outro',
  '-- cadastro esbarra em fn_cpf_ja_cadastrado (o portao de createServidor/updateServidor desde que',
  '-- o indice unico caiu), e a unica saida que ele oferece e marcar "vinculo adicional" — que e',
  '-- exatamente a caixa cujo uso indevido cria a duplicata (armadilha 50 do CLAUDE.md). Nao havia',
  '-- caminho nenhum: a tela apontava o problema e mandava fazer o que o sistema nao permite',
  '-- (armadilha 44).',
  '--',
  '-- MEDIDO EM PRODUCAO EM 11/09/2026, antes de decidir:',
  '--',
  '--   * 2.643 servidores ativos nao mesclados; 62 grupos com NOME identico.',
  '--   * 61 desses grupos tem o MESMO CPF dos dois lados (ja eram mesclaveis). 1 nao tem.',
  '--   * o unico grupo com CPF divergente e por nome: SAMU-SMS, dois cadastros criados com 25 min',
  '--     de diferenca no mesmo dia, mesma unidade, mesmo cargo, mesmo telefone, um deles com',
  '--     matricula temporaria — assinatura de recadastro por engano.',
  '--   * 10 dos 156 grupos suspeitos tem CPF divergente: 1 por nome, 6 por TELEFONE e 3 por EMAIL',
  '--     (um deles e um endereco compartilhado por 12 pessoas).',
  '--',
  '-- 🚨 E NAO E SO O CPF QUE DIVERGE NAQUELE GRUPO. PIS, data de nascimento (20 anos de',
  '-- diferenca) e NOME DA MAE tambem divergem. Uma tela que dissesse apenas "os CPFs sao',
  '-- diferentes, confirma?" esconderia justamente o que decide. Por isso a peca central desta',
  '-- migration nao e a escotilha — e fn_divergencias_identidade_servidor, que poe a identidade',
  '-- inteira na frente de quem vai declarar.',
  '--',
  '-- O QUE MUDA:',
  '--',
  '--   1. fn_divergencias_identidade_servidor (NOVA) — os campos de identidade que divergem.',
  '--   2. fn_impedimentos_mesclagem_servidor ganha p_confirmar_identidade (DEFAULT false).',
  '--      So o impedimento cpf_divergente e suprimido. Todos os outros continuam.',
  '--   3. fn_mesclar_servidores ganha p_confirmar_identidade (DEFAULT false), exige MOTIVO',
  '--      escrito quando a declaracao e efetiva, e NAO copia campo de pessoa nesse caso.',
  '--',
  '-- O QUE NAO MUDA, e cada um tem motivo medido:',
  '--',
  '--   * DEFAULT false nos dois lados: quem nao declara nada continua barrado, exatamente como',
  '--     antes. O lado seguro e o default (armadilha 41).',
  '--   * a declaracao so tem efeito quando o CPF DE FATO diverge (v_declarada). Nas outras 61',
  '--     mesclagens ela nao autoriza nada e nao muda comportamento nenhum.',
  '--   * sem_cpf (nenhum dos dois tem CPF) continua impedimento DURO. Nao ha caso medido, e sem',
  '--     CPF em lado nenhum nao ha nem o que declarar.',
  '--   * escala_sobreposta, origem/destino ja mesclados, colisao de unicidade: intactos.',
  '--   * quem mescla continua sendo RH Geral ou Administrador Geral (20260911120000).',
  '--   * a TELA so oferece este caminho em grupo de NOME IDENTICO com exatamente 2 cadastros.',
  '--     Telefone e email continuam fechados: sao compartilhados, e ha um email com 12 pessoas.',
  '--',
  '-- ⚠️ BLOCOS GERADOS por scratchpad/gen_mesclagem_declarada.js a partir das versoes VIGENTES',
  '-- (impedimentos: 20260906100000; mesclagem: 20260911120000 — NAO 20260904130000, onde as duas',
  '-- nasceram). Nao editar a mao: o gerador confere 14 invariantes antes e 12 depois, e ABORTA se',
  '-- a contagem divergir. E ele que garante que o GUC da imutabilidade da marcacao, a varredura',
  '-- por pg_index, a fusao de escala antes do laco generico e o "inativa, nunca exclui"',
  '-- atravessaram a copia (armadilha 1).',
  '--',
  '-- ⚠️ ASSINATURA NOVA E OBJETO NOVO (armadilha 41): nasce com EXECUTE para PUBLIC, entao os',
  '-- REVOKE/GRANT sao reescritos aqui; e as assinaturas antigas precisam de DROP, senao duas',
  '-- sobrecargas fazem o PostgREST devolver PGRST203.',
  '-- ============================================================================',
  '',
  '',
)

const DIVERGENCIAS = L(
  '-- ============================================================================',
  '-- 1. A IDENTIDADE QUE DIVERGE — a informacao que faltava na tela',
  '-- ============================================================================',
  '-- Devolve uma linha por campo de identidade preenchido NOS DOIS cadastros e diferente entre',
  '-- eles. E leitura pura: nao decide nada, nao bloqueia nada.',
  '--',
  '-- ⚠️ Campo preenchido em UM lado so NAO e divergencia. Ausencia nao sugere pessoa diferente, e',
  '-- listar ausencia junto afogaria o sinal que importa no ruido de ficha incompleta.',
  '--',
  '-- ⚠️ A lista e explicita, como a allowlist de campos de pessoa de fn_mesclar_servidores, e pelo',
  '-- mesmo motivo invertido: aqui, ESQUECER um campo e pior do que ter um a mais — o campo',
  '-- esquecido e uma divergencia que ninguem ve antes de declarar. Coluna nova de identidade',
  '-- entra aqui junto.',
  'DROP FUNCTION IF EXISTS public.fn_divergencias_identidade_servidor(uuid, uuid);',
  '',
  'CREATE FUNCTION public.fn_divergencias_identidade_servidor(',
  '    p_origem  uuid,',
  '    p_destino uuid',
  ')',
  'RETURNS TABLE (',
  '    campo         text,',
  '    rotulo        text,',
  '    valor_origem  text,',
  '    valor_destino text',
  ')',
  'LANGUAGE sql',
  'STABLE',
  'SECURITY DEFINER',
  'SET search_path = public',
  'AS $fn$',
  '    WITH o AS (SELECT * FROM public.servidores WHERE id = p_origem),',
  '         d AS (SELECT * FROM public.servidores WHERE id = p_destino),',
  '    -- Normalizacao por TIPO de campo: documento vira so digitos (018.123.456-78 e 01812345678',
  '    -- sao o mesmo CPF), nome vira caixa alta sem acento e sem espaco duplo, o resto vira texto',
  '    -- aparado. Sem isto, diferenca de digitacao viraria "identidade divergente" e a tela',
  '    -- gritaria a toa — aviso que grita a toa e o caminho mais curto para ninguem mais ler',
  '    -- nenhum.',
  '    pares AS (',
  '        SELECT * FROM (VALUES',
  "            ('cpf',             'CPF',                 1, public.fn_cpf_normalizado((SELECT cpf FROM o)),             public.fn_cpf_normalizado((SELECT cpf FROM d)),             (SELECT cpf FROM o),             (SELECT cpf FROM d)),",
  "            ('pis_pasep',       'PIS/PASEP',           2, nullif(regexp_replace(COALESCE((SELECT pis_pasep FROM o), ''), '\\D', '', 'g'), ''), nullif(regexp_replace(COALESCE((SELECT pis_pasep FROM d), ''), '\\D', '', 'g'), ''), (SELECT pis_pasep FROM o), (SELECT pis_pasep FROM d)),",
  "            ('data_nascimento', 'data de nascimento',  3, (SELECT data_nascimento::text FROM o),                      (SELECT data_nascimento::text FROM d),                      (SELECT data_nascimento::text FROM o), (SELECT data_nascimento::text FROM d)),",
  "            ('nome_mae',        'nome da mae',         4, public.fn_texto_identidade_normalizado((SELECT nome_mae FROM o)), public.fn_texto_identidade_normalizado((SELECT nome_mae FROM d)), (SELECT nome_mae FROM o), (SELECT nome_mae FROM d)),",
  "            ('nome_pai',        'nome do pai',         5, public.fn_texto_identidade_normalizado((SELECT nome_pai FROM o)), public.fn_texto_identidade_normalizado((SELECT nome_pai FROM d)), (SELECT nome_pai FROM o), (SELECT nome_pai FROM d)),",
  "            ('sexo',            'sexo',                6, public.fn_texto_identidade_normalizado((SELECT sexo::text FROM o)), public.fn_texto_identidade_normalizado((SELECT sexo::text FROM d)), (SELECT sexo::text FROM o), (SELECT sexo::text FROM d)),",
  "            ('rg_numero',       'RG',                  7, nullif(regexp_replace(COALESCE((SELECT rg_numero FROM o), ''), '\\D', '', 'g'), ''), nullif(regexp_replace(COALESCE((SELECT rg_numero FROM d), ''), '\\D', '', 'g'), ''), (SELECT rg_numero FROM o), (SELECT rg_numero FROM d))",
  '        ) AS t(campo, rotulo, ordem, norm_o, norm_d, bruto_o, bruto_d)',
  '    )',
  '    SELECT p.campo, p.rotulo, p.bruto_o, p.bruto_d',
  '      FROM pares p',
  '     WHERE p.norm_o IS NOT NULL',
  '       AND p.norm_d IS NOT NULL',
  '       AND p.norm_o <> p.norm_d',
  '     ORDER BY p.ordem',
  '$fn$;',
  '',
  "COMMENT ON FUNCTION public.fn_divergencias_identidade_servidor(uuid, uuid) IS",
  "    'Campos de identidade preenchidos nos dois cadastros e diferentes entre si. Leitura pura, "
    + "para a tela poder mostrar a identidade inteira antes de alguem declarar que sao a mesma pessoa.';",
  '',
  'REVOKE ALL ON FUNCTION public.fn_divergencias_identidade_servidor(uuid, uuid) FROM PUBLIC, anon;',
  'GRANT EXECUTE ON FUNCTION public.fn_divergencias_identidade_servidor(uuid, uuid) TO authenticated, service_role;',
  '',
  '',
)

const NORMALIZADOR = L(
  '-- ============================================================================',
  '-- 0. NORMALIZACAO DE TEXTO DE IDENTIDADE',
  '-- ============================================================================',
  '-- Caixa alta, sem acento, sem espaco duplo. Usada so para COMPARAR — o que a tela exibe e',
  '-- sempre o valor bruto de cada ficha.',
  '--',
  '-- ⚠️ translate() em vez da extensao unaccent de proposito: a extensao pode nao estar instalada',
  '-- e o unico efeito de errar aqui e acusar divergencia a mais num acento. Preso a nao instalar',
  '-- extensao por causa de uma comparacao de nome de mae.',
  'CREATE OR REPLACE FUNCTION public.fn_texto_identidade_normalizado(p_valor text)',
  'RETURNS text',
  'LANGUAGE sql',
  'IMMUTABLE',
  'AS $fn$',
  '    SELECT nullif(',
  '        btrim(regexp_replace(',
  '            translate(upper(COALESCE(p_valor, \'\')),',
  '                      \'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑ\',',
  '                      \'AAAAAEEEEIIIIOOOOOUUUUCN\'),',
  '            \'\\s+\', \' \', \'g\')),',
  '        \'\')',
  '$fn$;',
  '',
  'REVOKE ALL ON FUNCTION public.fn_texto_identidade_normalizado(text) FROM PUBLIC, anon;',
  'GRANT EXECUTE ON FUNCTION public.fn_texto_identidade_normalizado(text) TO authenticated, service_role;',
  '',
  '',
)

const BLOCO_IMP = L(
  '-- ============================================================================',
  '-- 2. O QUE IMPEDE A MESCLAGEM — agora com a escotilha declarada',
  '-- ============================================================================',
  '-- ⚠️ BLOCO GERADO (ver cabecalho). Copia da versao vigente (20260906100000) com UMA mudanca de',
  '-- comportamento: o impedimento cpf_divergente passa a respeitar p_confirmar_identidade.',
  '--',
  '-- ⚠️ DROP da assinatura de 2 argumentos: RETURNS TABLE nao aceita CREATE OR REPLACE com lista',
  '-- de colunas diferente (42P13), e deixar as duas vivas daria PGRST203 em qualquer chamada de 2',
  '-- argumentos, que e justamente a que a tela fazia ate agora.',
  'DROP FUNCTION IF EXISTS public.fn_impedimentos_mesclagem_servidor(uuid, uuid);',
  'DROP FUNCTION IF EXISTS public.fn_impedimentos_mesclagem_servidor(uuid, uuid, boolean);',
  '',
  imp,
  '',
  "COMMENT ON FUNCTION public.fn_impedimentos_mesclagem_servidor(uuid, uuid, boolean) IS",
  "    'O que impede mesclar este par. Com p_confirmar_identidade, o impedimento por CPF divergente "
    + "da lugar a uma declaracao explicita de quem mescla; todos os demais continuam.';",
  '',
  'REVOKE ALL ON FUNCTION public.fn_impedimentos_mesclagem_servidor(uuid, uuid, boolean) FROM PUBLIC, anon;',
  'GRANT EXECUTE ON FUNCTION public.fn_impedimentos_mesclagem_servidor(uuid, uuid, boolean) TO authenticated, service_role;',
  '',
  '',
)

const BLOCO_MESC = L(
  '-- ============================================================================',
  '-- 3. MESCLAR — com declaracao de identidade, motivo obrigatorio e sem copiar ficha',
  '-- ============================================================================',
  '-- ⚠️ BLOCO GERADO (ver cabecalho). Copia da versao vigente (20260911120000).',
  '--',
  '-- ⚠️ DROP da assinatura de 3 argumentos pelo mesmo motivo do bloco anterior: com as duas vivas,',
  '-- a chamada de 3 argumentos que a tela faz hoje viraria PGRST203.',
  'DROP FUNCTION IF EXISTS public.fn_mesclar_servidores(uuid, uuid, text);',
  'DROP FUNCTION IF EXISTS public.fn_mesclar_servidores(uuid, uuid, text, boolean);',
  '',
  mesc,
  '',
  "COMMENT ON FUNCTION public.fn_mesclar_servidores(uuid, uuid, text, boolean) IS",
  "    'Move todo vinculo do cadastro duplicado para o que fica e inativa o duplicado. Com "
    + "p_confirmar_identidade e CPF divergente: exige motivo escrito e NAO copia campo de pessoa, "
    + "porque a ficha duplicada pode trazer dado de terceiro.';",
  '',
  'REVOKE ALL ON FUNCTION public.fn_mesclar_servidores(uuid, uuid, text, boolean) FROM PUBLIC, anon;',
  'GRANT EXECUTE ON FUNCTION public.fn_mesclar_servidores(uuid, uuid, text, boolean) TO authenticated, service_role;',
  '',
  '',
)

const CONFERENCIA = L(
  '-- ============================================================================',
  '-- CONFERENCIA — EXECUTA as funcoes, nos DOIS sentidos',
  '-- ============================================================================',
  '-- ⚠️ Conferir que a funcao EXISTE nao serve (armadilha 42): a que quebrou em producao existia.',
  '-- Aqui a conferencia CHAMA cada funcao e confere o resultado.',
  '--',
  '-- Os dois sentidos em cada caso. Afrouxar so um lado e o que transforma "liberar o caso real"',
  '-- em "liberar mesclagem de pessoas diferentes":',
  '--   * sem declaracao, o par com CPF divergente CONTINUA impedido;',
  '--   * com declaracao, ele passa — e nenhum outro impedimento sumiu junto.',
  '--',
  '-- ⚠️ A chamada de fn_mesclar_servidores e feita com motivo CURTO, que tem que falhar ANTES de',
  '-- qualquer escrita. Se ela NAO falhar, a conferencia levanta excecao e a transacao inteira da',
  '-- migration volta atras — inclusive a mesclagem que teria acontecido.',
  'DO $conf$',
  'DECLARE',
  '    v_o        uuid;',
  '    v_d        uuid;',
  '    v_n        integer;',
  '    v_tem_cpf  boolean;',
  '    v_msg      text;',
  'BEGIN',
  '    -- Um par real com CPF divergente e nome identico. Se nao houver nenhum, a conferencia de',
  '    -- comportamento e pulada (base limpa e resultado valido, nao motivo para abortar).',
  '    SELECT a.id, b.id INTO v_o, v_d',
  '      FROM public.servidores a',
  '      JOIN public.servidores b',
  '        ON public.fn_texto_identidade_normalizado(a.nome) = public.fn_texto_identidade_normalizado(b.nome)',
  '       AND a.id < b.id',
  "     WHERE a.status = 'Ativo' AND b.status = 'Ativo'",
  '       AND a.mesclado_em_servidor_id IS NULL AND b.mesclado_em_servidor_id IS NULL',
  '       AND public.fn_cpf_normalizado(a.cpf) IS NOT NULL',
  '       AND public.fn_cpf_normalizado(b.cpf) IS NOT NULL',
  '       AND public.fn_cpf_normalizado(a.cpf) <> public.fn_cpf_normalizado(b.cpf)',
  '     LIMIT 1;',
  '',
  '    IF v_o IS NULL THEN',
  '        RAISE NOTICE $$CONFERENCIA DE COMPORTAMENTO PULADA: nenhum par ativo com nome identico e CPF divergente.$$;',
  '    ELSE',
  '        -- 1) a divergencia de identidade e ENCONTRADA, e o CPF esta nela',
  '        SELECT count(*), bool_or(campo = $$cpf$$)',
  '          INTO v_n, v_tem_cpf',
  '          FROM public.fn_divergencias_identidade_servidor(v_o, v_d);',
  '        IF v_n = 0 OR NOT v_tem_cpf THEN',
  '            RAISE EXCEPTION $$FALHOU: fn_divergencias_identidade_servidor devolveu % linha(s), cpf presente=%$$, v_n, v_tem_cpf;',
  '        END IF;',
  '        RAISE NOTICE $$ok: identidade divergente em % campo(s), CPF entre eles.$$, v_n;',
  '',
  '        -- 2) SEM declaracao, o impedimento por CPF continua (o sentido que protege)',
  '        SELECT count(*) INTO v_n',
  '          FROM public.fn_impedimentos_mesclagem_servidor(v_o, v_d)',
  '         WHERE motivo = $$cpf_divergente$$;',
  '        IF v_n <> 1 THEN',
  '            RAISE EXCEPTION $$FALHOU: sem declaracao, cpf_divergente deveria aparecer 1 vez, apareceu %.$$, v_n;',
  '        END IF;',
  '',
  '        -- 2b) o default sozinho basta: chamada de 2 argumentos continua barrando',
  '        SELECT count(*) INTO v_n',
  '          FROM public.fn_impedimentos_mesclagem_servidor(v_o, v_d, false)',
  '         WHERE motivo = $$cpf_divergente$$;',
  '        IF v_n <> 1 THEN',
  '            RAISE EXCEPTION $$FALHOU: com p_confirmar_identidade=false, cpf_divergente sumiu.$$;',
  '        END IF;',
  '        RAISE NOTICE $$ok: sem declaracao o par continua impedido.$$;',
  '',
  '        -- 3) COM declaracao, o cpf_divergente sai — e SO ele',
  '        SELECT count(*) INTO v_n',
  '          FROM public.fn_impedimentos_mesclagem_servidor(v_o, v_d, true)',
  '         WHERE motivo = $$cpf_divergente$$;',
  '        IF v_n <> 0 THEN',
  '            RAISE EXCEPTION $$FALHOU: com declaracao, cpf_divergente ainda aparece.$$;',
  '        END IF;',
  '        RAISE NOTICE $$ok: com declaracao o par passa.$$;',
  '',
  '        -- 4) declarar SEM motivo escrito nao mescla nada',
  '        BEGIN',
  '            PERFORM public.fn_mesclar_servidores(v_o, v_d, $$erro$$, true);',
  '            RAISE EXCEPTION $$FALHOU: mesclagem declarada passou com motivo de 4 caracteres.$$;',
  '        EXCEPTION',
  '            WHEN check_violation THEN',
  '                GET STACKED DIAGNOSTICS v_msg = MESSAGE_TEXT;',
  '                IF v_msg NOT LIKE $$%motivo escrito%$$ THEN',
  '                    RAISE EXCEPTION $$FALHOU: recusou por outro motivo: %$$, v_msg;',
  '                END IF;',
  '                RAISE NOTICE $$ok: declaracao sem motivo escrito e recusada.$$;',
  '        END;',
  '    END IF;',
  '',
  '    -- 5) as assinaturas antigas nao podem ter sobrado (PGRST203)',
  '    SELECT count(*) INTO v_n FROM pg_proc p',
  '      JOIN pg_namespace n ON n.oid = p.pronamespace',
  "     WHERE n.nspname = 'public' AND p.proname = 'fn_mesclar_servidores';",
  '    IF v_n <> 1 THEN',
  '        RAISE EXCEPTION $$FALHOU: fn_mesclar_servidores tem % sobrecarga(s); o PostgREST devolveria PGRST203.$$, v_n;',
  '    END IF;',
  '    SELECT count(*) INTO v_n FROM pg_proc p',
  '      JOIN pg_namespace n ON n.oid = p.pronamespace',
  "     WHERE n.nspname = 'public' AND p.proname = 'fn_impedimentos_mesclagem_servidor';",
  '    IF v_n <> 1 THEN',
  '        RAISE EXCEPTION $$FALHOU: fn_impedimentos_mesclagem_servidor tem % sobrecarga(s).$$, v_n;',
  '    END IF;',
  '    RAISE NOTICE $$ok: uma assinatura de cada, sem ambiguidade.$$;',
  '',
  '    -- 6) anon nao executa nenhuma das quatro',
  '    SELECT count(*) INTO v_n FROM (VALUES',
  "        ('public.fn_divergencias_identidade_servidor(uuid, uuid)'),",
  "        ('public.fn_texto_identidade_normalizado(text)'),",
  "        ('public.fn_impedimentos_mesclagem_servidor(uuid, uuid, boolean)'),",
  "        ('public.fn_mesclar_servidores(uuid, uuid, text, boolean)')",
  '    ) AS f(assinatura)',
  "     WHERE has_function_privilege('anon', f.assinatura, 'EXECUTE');",
  '    IF v_n <> 0 THEN',
  '        RAISE EXCEPTION $$FALHOU: % funcao(oes) continuam executaveis por anon.$$, v_n;',
  '    END IF;',
  '',
  '    -- 7) e authenticated continua executando as tres que a tela usa (revogar demais derruba a',
  '    --    tela com a mesma discricao — a licao da 20260827050000)',
  '    SELECT count(*) INTO v_n FROM (VALUES',
  "        ('public.fn_divergencias_identidade_servidor(uuid, uuid)'),",
  "        ('public.fn_impedimentos_mesclagem_servidor(uuid, uuid, boolean)'),",
  "        ('public.fn_mesclar_servidores(uuid, uuid, text, boolean)')",
  '    ) AS f(assinatura)',
  "     WHERE has_function_privilege('authenticated', f.assinatura, 'EXECUTE');",
  '    IF v_n <> 3 THEN',
  '        RAISE EXCEPTION $$FALHOU: authenticated perdeu acesso (% de 3).$$, v_n;',
  '    END IF;',
  '    RAISE NOTICE $$ok: anon fora, authenticated dentro.$$;',
  '',
  '    RAISE NOTICE $$CONFERENCIA OK.$$;',
  'END;',
  '$conf$;',
  '',
)

const sql = [CABECALHO, NORMALIZADOR, DIVERGENCIAS, BLOCO_IMP, BLOCO_MESC, CONFERENCIA].join(EOL)

// portao final do montador
const exigidos = [
  ['dollar-quote das funcoes fechado', (sql.match(/\$fn\$/g) || []).length % 2 === 0],
  ['conferencia presente', sql.includes('CONFERENCIA OK')],
  ['drop da assinatura antiga de mesclar', sql.includes('DROP FUNCTION IF EXISTS public.fn_mesclar_servidores(uuid, uuid, text);')],
  ['drop da assinatura antiga de impedimentos', sql.includes('DROP FUNCTION IF EXISTS public.fn_impedimentos_mesclagem_servidor(uuid, uuid);')],
  ['grant reescrito para a assinatura nova', sql.includes('GRANT EXECUTE ON FUNCTION public.fn_mesclar_servidores(uuid, uuid, text, boolean)')],
]
for (const [nome, ok] of exigidos) {
  if (!ok) abortar(`montagem: ${nome}`)
  console.log(`  [ok] ${nome}`)
}

fs.writeFileSync(SAIDA, sql)
console.log(`\n[ok] ${path.relative(RAIZ, SAIDA)} — ${sql.split(EOL).length} linhas`)
